version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16
    volumes:
      - ..:/workspace:cached
    env_file: ../.env
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ../.env
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    restart: always
    volumes:
      - adonisjs-redis-data:/data
    env_file: ../.env
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

volumes:
  postgres-data:
  adonisjs-redis-data:
