version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16
    volumes:
      - ..:/workspace:cached
    env_file: ../.env
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ../packages/server/.env
    ports:
      - 5432:5432

volumes:
  postgres-data:
