version: '3.9'

services:
  app:
    build:
      args:
        USERNAME: node
        VARIANT: 16
    volumes:
      - ..:/workspace:cached
      - bash_history:/commandhistory
      - node_modules:/workspace/node_modules
      - pnpm_store:/home/node/.local/share/pnpm/store
      - vscode_extensions:/home/node/.vscode-server/extensions
    env_file: ../.env
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ../.env
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    env_file: ../.env
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

volumes:
  bash_history:
  node_modules:
  pnpm_store:
  postgres_data:
  redis_data:
  vscode_extensions:
